blank_issues_enabled: false
contact_links:
  - name: Return to the app
    url: https://devin503.github.io/weather-project
    about: In case you need to retrace your steps again, go ahead and return to the app here.
